---
title: Fit the FDA model
authors:
  - name: Nicholas Harbour
format: 
  html:
    embed-resources: true
    code-fold: true
    number-sections: true
    toc: true
    toc-depth: 3
    date: now
    date-modified: last-modified
    date-format: "MMMM DD, YYYY, HH:mm:ss"
jupyter: python3
---

# Load in the data


Import python libraries required for the analysis
```{python}

# Import the necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import datetime as dt
from scipy.special import i0 
from scipy.optimize import minimize
from scipy.stats import circvar
from matplotlib.ticker import MaxNLocator
from scipy.optimize import differential_evolution
from scipy.optimize import NonlinearConstraint

# import functions 
from functions import *

```

Load in the data
```{python}

df_com = pd.read_csv("Data/Hormone_time_series_data_interpolated.csv")

num = df_to_numpy(df_com, "Cortisol")

common_t = df_com["NewTime"].iloc[0:72].values

```



# Fit the basis functions

We can write our simple model for the data as a sum of basis functions:

$$
  x_i(t) = \sum_{j=1}^k w_{i,j} \phi_j(t - d_j) 
$$

Where $x_i(t)$ is the value of the $i$'th time series at time $t$. $w_{i,j}$ are the weight of the $j$'th basis function for the person $i$. $\phi_j(t)$ is the basis function and $k$ is the number of basis functions. 

We take the basis functions to be von Mises distribution, which is given by:

$$
  f(x | \mu, \kappa) = \frac{e^{\kappa \cos(x - \mu)}}{2\pi I_0(\kappa)}
$$

These $\mu$'s are equivalent to the shift parameter we wrote down previously.

And to fit our von Mises basis we can do the following:

In the model fit we have the following constraints/bounds:

- The peak location is between $-\pi$ and $\pi$.
- The amplitude/weight is between 0 and 40. (always positive)
- The dispersion is between 0 and 200.

```{python}

t = np.linspace(-np.pi, np.pi, num=72)

def Von_Mises_model(params,t):
    '''
    Our functional data analysis approach uses a sum of von Mises basis functions.
    We consider 3 basis functions, roughly inspired by the idea of one for each of the three meals (breakfast, lunch and dinner).

    Inputs:
    t: time domain
    params: list of parameters for the von Mises basis functions
        params[0] = mean location
        params[1] = amplitude / weight
        params[2] = dispersion / standard deviation
    Outputs:
    y: np.array of the same size as x, the model fit (sum of the basis functions)
    '''

    y = np.zeros_like(t)
    for i in range(0, len(params)-1, 3):
        ctr = params[i]
        amp = params[i+1]
        wid = params[i+2]
        y = y + amp*np.exp(wid*np.cos(t-ctr))/(2*np.pi*i0(wid))
    # Add a constant parameter
    y = y + params[-1]
    return y


def NRMSE(data,model):
    '''
    Normalized root mean square error

    Inputs:
    data: np.array / list of the data points
    model: np.array / list of the model fit
    Outputs:
    nRMSE: normalized root mean square error
    '''
    n_points = len(data)
    MSE = 0
    for i in range(n_points):
        MSE = MSE + (data[i] - model[i])**2
    MSE = MSE / n_points
    RSME = np.sqrt(MSE)
    nRMSE = RSME / np.mean(data)
    return nRMSE


def objective_function(params,t,data):
    '''
    Objective function to be minimized
    '''
    # Fit the model
    y = Von_Mises_model(params,t)
    return NRMSE(data, y) # error between data and model to be minimized


# Wake time peak
t1 = map_range_to_pi(28) # 4am
t2 = map_range_to_pi(35) # 11am 
# lunch time peak
t3 = map_range_to_pi(35.1) # 12am
t4 = map_range_to_pi(16) # 4pm 
# Dinner time peak
t5 = map_range_to_pi(17) # 5pm
t6 = map_range_to_pi(22) # 9pm

# The constraint should be greater than 0, thus we get the following inequalities
# t1 < x[0] < t2
# t3 < x[3] < t4
# t5 < x[6] < t6
# The constraints are given by the following inequalities

cons = ({'type': 'ineq', 'fun': lambda x:  x[0] - t1},  # x[0] ≥ t1
        {'type': 'ineq', 'fun': lambda x:  t2 - x[0]},  # x[0] ≤ t2

        {'type': 'ineq', 'fun': lambda x:  x[3] - t3},  # x[3] ≥ t3
        {'type': 'ineq', 'fun': lambda x:  t4 - x[3]},  # x[3] ≤ t4

        {'type': 'ineq', 'fun': lambda x:  x[6] - t5},  # x[6] ≥ t5
        {'type': 'ineq', 'fun': lambda x:  t6 - x[6]})  # x[6] ≤ t6


def constraint_fun(x):
    return np.array([
        x[0] - t1,   # x[0] > t1
        t2 - x[0],   # x[0] < t2
        max(x[3] - t3, t4 - x[3]),  # circular constraint for x[3]
        x[6] - t5,
        t6 - x[6]
    ])

nonlin_con = NonlinearConstraint(constraint_fun, 0, np.inf)

def fit_von_mises(time_series, n_basis):

    '''
    Fit the von Mises basis model to a single time series by minimizing the error between the data and the model (objective function).
    Inputs:
    time_series: np.array / list of the data points
    n_basis: number of basis functions to fit
    Outputs:

    '''

    guess = np.zeros(3*n_basis + 1)

    bounds = []  

    for k in range(n_basis):
        # Peak location (no bounds)
        bounds.append((-np.pi, np.pi))  # mean/peak location

        # Amplitude (positive)
        bounds.append((0, 40))

        # Dispersion (peaky control)
        bounds.append((2, 200)) # Higer values give a more peaky distribution

        if k == 2:
            # Add a constant parameter to the model
            bounds.append((0, 10))  # Constant offset

        # Make sure the initial guess is within the bounds / statify the constraints
        if k == 0:
            guess[3*k] = np.random.uniform(t1,t2)
        elif k == 1:
            # The lunch time peak wraps around the time axis
            test= np.random.uniform(-np.pi,np.pi)
            while not (test > t3 or test < t4):
                test = np.random.uniform(-np.pi,np.pi)
        elif k == 2:
            guess[3*k] = np.random.uniform(t5,t6)
        
        # Amplitute / weight
        guess[3*k+1] = np.random.uniform(0,40)
        # Dispersion / standard deviation
        guess[3*k+2] = np.random.uniform(2,200)

    guess[-1] = np.random.uniform(0, 10)  # Constant offset

    res = differential_evolution(objective_function,bounds=bounds, args=(t,time_series,),constraints=nonlin_con)
    #popt, pcov = curve_fit(func, t, time_series, p0=guess, maxfev=100000000)

    return  res

```

Example fit for a single participant
```{python}

pat_ind = 101

res = fit_von_mises(num[pat_ind], 3)
fit_params = res.x
fit = Von_Mises_model(fit_params, t)


plt.plot(t, num[pat_ind], 'bo-')
plt.plot(t, fit , 'r-')
plt.legend(['data', 'model fit'])

ss_res = NRMSE(num[pat_ind],fit)
# # Adding text without box on the plot.
plt.text(0.01, 0.8,  f"nRMSE = {ss_res:.4}", ha='left', va='top', transform=plt.gca().transAxes)

for i in range(0, len(fit_params)-1, 3):
    ctr = fit_params[i]
    amp = fit_params[i+1]
    wid = fit_params[i+2]
    y = amp*np.exp(wid*np.cos(t-ctr))/(2*np.pi*i0(wid))
    plt.plot(t, y,'--', alpha = 0.8)

plt.axhline(y = fit_params[-1], color='m', linestyle='--', label='Constant offset')

plt.title("Example Von Mises fit for single participant")
plt.xlabel("Time (hours)")
plt.ylabel("Cortisol")
plt.xticks(np.linspace(-np.pi,np.pi,7), ['12', '16', '20', '00', '04', '08', '12'])  # Set x-tick labels
plt.show()

```


## Fit 3 basis function to all patients

Lets fit 3 basis function to all patients


```{python}
n_basis = 3
ss_res_save = np.zeros(len(num))
basis_save = np.zeros([len(num), 3*n_basis+1])
basis1 = np.zeros(3)
basis2 = np.zeros(3)
basis3 = np.zeros(3)
basis_constant = np.zeros(1)

for i in range(len(num)):
    res = fit_von_mises(num[i], 3)
    fit_params = res.x
    fit = Von_Mises_model(fit_params, t)
    basis1 = fit_params[0:3]
    basis2 = fit_params[3:6]
    basis3 = fit_params[6:9]
    basis_constant = fit_params[-1]
    
    ss_res_save[i] = NRMSE(num[i],fit)

    # Order the basis functions by the weight (the final parameter)
    #basis1, basis2, basis3 = order_basis(basis1, basis2, basis3)

    basis_save[i,0:3] = basis1
    basis_save[i,3:6] = basis2
    basis_save[i,6:9] = basis3
    basis_save[i,9] = basis_constant


```



Plot a number of the model fits on a single plot

```{python}


def plot_single(popt, t, time_series,ax, ss_res = -1):
    ax.plot(t, time_series, 'bo-')
    ax.plot(t, Von_Mises_model(popt,t) , 'r-')
    ax.text(0.01, 0.99, f"nRMSE = {ss_res:.2f}", ha='left', va='top', 
            transform=ax.transAxes, fontsize=12, color='black')
    
    for i in range(0, len(popt)-1, 3):
        ctr = popt[i]
        amp = popt[i+1]
        wid = popt[i+2]
        y = amp*np.exp(wid*np.cos(t-ctr))/(2*np.pi*i0(wid))
        ax.plot(t, y,'--', alpha = 0.8)

    ax.axhline(y = popt[-1], color='m', linestyle='--', label='Constant offset')
    # Set y-axis ticks to be integers only
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
```

```{python}

rows = 8
cols = 5
fig, ax = plt.subplots(rows,cols , figsize=(21, 28))
plt.subplots_adjust(hspace=0.1, wspace=0.15)  # Adjust space between subplots


for i in range(rows):
    for j in range(cols):
      if i*10 + j >= len(num):
          break
      plot_single(basis_save[i*cols + j,:], t, num[i*cols + j,:], ax[i,j], ss_res_save[i*cols + j])

      # Remove x-tick labels for all plots except for the last row
      if i < rows - 1:  # If not in the last row
            ax[i, j].set_xticklabels([])  # Remove x-tick labels
      else:
            ax[i, j].set_xticks(np.linspace(-np.pi,np.pi,7), ['12', '16', '20', '00', '04', '08', '12'])  # Set x-tick labels




# Add a legend at the center top of the figure
fig.legend(['Data', 'Fit', 'Basis 1', 'Basis 2', 'Basis 3'], loc='upper center', ncol=5, fontsize=16, bbox_to_anchor=(0.5, 0.9))


plt.show()

```




### View error in model fits

Lets check a histogram of the model fits to make sure it is doing a good job.

```{python}

plt.hist(ss_res_save)
plt.title("Histogram of R squared values")
plt.xlabel("nRMSE / error")
plt.ylabel("Frequency")

plt.show()


nRMSE_threshold = 0.45

plt.plot(ss_res_save, 'o')
plt.axhline(y = nRMSE_threshold, color = 'r', linestyle = '--')
plt.ylabel("nRMSE")
plt.xlabel("Sample")

plt.show()

```


Based on the histogram there are a handful that have R squared values of over 0.4 we will look at these individually. - A lot of these can be explained by the fact that there are 2 peaks in a time peroid which the constraints only allow for a single peak / basis function, we are ok with this as we don't want to increase the complexity by adding more basis functions.

```{python}

ss_res_save_over = ss_res_save > nRMSE_threshold
print(f"Number of fits over threshold (nRMSE $>{nRMSE_threshold}$) is: {np.sum(ss_res_save_over)}")

num_over = num[ss_res_save_over]
popt_over = basis_save[ss_res_save_over]

for j in range(len(num_over)):
    plt.plot(t, num_over[j],'bo-')
    plt.plot(t, Von_Mises_model(popt_over[j,:],t) , 'r-')
    plt.text(0.01, 0.99, f"nRMSE = {ss_res_save[ss_res_save_over][j]:.2f}", ha='left', va='top', 
            transform=plt.gca().transAxes, fontsize=12, color='black')
    for i in range(0, len(popt_over[0,:])-1, 3):
        ctr = popt_over[j,i]
        amp = popt_over[j,i+1]
        wid = popt_over[j,i+2]
        y = amp*np.exp(wid*np.cos(t-ctr))/(2*np.pi*i0(wid))
        plt.plot(t, y,'--', alpha = 0.8)
    plt.axhline(y = popt_over[j,-1], color='m', linestyle='--', label='Constant offset')

    plt.show()

```



### Visualize distribution of fitted model parameters

The shift parameter is the 1st parameter, the weight/amplitude is the 2nd and the width/dispersion is the 3rd.

```{python}

bs_bounds = np.array([t1, t2, t3, t4, t5, t6])


dum = 0
fig, ax = plt.subplots(3,3, figsize = (15,10))

for j in range(3):
    for i in range(3):
        ax[j,i].hist(basis_save[:,i + 3*j], bins = 100, density = True)
        ax[j,i].set_title(f"Distribution of parameter {i + 3*j}")



        if i == 0:
            ax[j,i].set_xlim([-np.pi,np.pi])
            ax[j,i].axvline(x = bs_bounds[dum], color = 'r', linestyle = '--')
            ax[j,i].axvline(x = bs_bounds[dum + 1], color = 'r', linestyle = '--')
            dum = dum +2

ax[2,0].set_ylim(0,3)
ax[0,0].set_xticks(np.linspace(-np.pi,np.pi,7), ['12', '16', '20', '00', '04', '08', '12'])  # Set x-tick labels
ax[1,0].set_xticks(np.linspace(-np.pi,np.pi,7), ['12', '16', '20', '00', '04', '08', '12'])  # Set x-tick labels
ax[2,0].set_xticks(np.linspace(-np.pi,np.pi,7), ['12', '16', '20', '00', '04', '08', '12'])  # Set x-tick labels

plt.show()

plt.hist(basis_save[:,9], bins = 100, density = True)
plt.title("Distribution of constant offset parameter")
plt.xlabel("Constant offset")
plt.ylabel("Density")
plt.show()

```


### Save the parameters into CSV


```{python}

# Define the column names
column_names = ['MasterID', 'Cortisol', 'param_values', 'Param0', 'param1', 'param2', 'param3','param4', 'param5','param6','param7', 'param8','param9' ,'R2']

# Create a list to hold the new rows
rows = []

MasterIDs = df_com["MasterID"].unique()

for i in range(len(MasterIDs)):
    new_row = {
        'MasterID': MasterIDs[i], 
        'Cortisol': num[i],
        'param_values': basis_save[i, :],
        'Param0': basis_save[i, 0],
        'param1': basis_save[i, 1],
        'param2': basis_save[i, 2],
        'param3': basis_save[i, 3],
        'param4': basis_save[i, 4],
        'param5': basis_save[i, 5],
        'param6': basis_save[i, 6],
        'param7': basis_save[i, 7],
        'param8': basis_save[i, 8],
        'param9': basis_save[i, 9],
        'R2': ss_res_save[i]
    }
    rows.append(new_row)

# Create the DataFrame from the list of rows
df_param = pd.DataFrame(rows, columns=column_names)

# Save the dataframe to csv
df_param.to_csv("Param_values.csv", index=False)

# Display the first few rows of dataframe
df_param.head()

```




# Aldosterone

```{python}

num_Aldo = df_to_numpy(df_com, "Aldo")

```


```{python}

n_basis = 3
ss_res_save = np.zeros(len(num_Aldo))
basis_save = np.zeros([len(num_Aldo), 3*n_basis+1])
basis1 = np.zeros(3)
basis2 = np.zeros(3)
basis3 = np.zeros(3)
basis_constant = np.zeros(1)

for i in range(len(num_Aldo)):
    print(i)
    if np.isnan(num_Aldo[i]).any():
        continue
    res = fit_von_mises(num_Aldo[i], 3)
    fit_params = res.x
    fit = Von_Mises_model(fit_params, t)
    basis1 = fit_params[0:3]
    basis2 = fit_params[3:6]
    basis3 = fit_params[6:9]
    basis_constant = fit_params[-1]
    
    ss_res_save[i] = NRMSE(num_Aldo[i],fit)

    # Order the basis functions by the weight (the final parameter)
    #basis1, basis2, basis3 = order_basis(basis1, basis2, basis3)

    basis_save[i,0:3] = basis1
    basis_save[i,3:6] = basis2
    basis_save[i,6:9] = basis3
    basis_save[i,9] = basis_constant



```


```{python}

rows = 8
cols = 5
fig, ax = plt.subplots(rows,cols , figsize=(21, 28))
plt.subplots_adjust(hspace=0.1, wspace=0.15)  # Adjust space between subplots


for i in range(rows):
    for j in range(cols):
      if i*10 + j >= len(num):
          break
      plot_single(basis_save[i*cols + j,:], t, num_Aldo[i*cols + j,:], ax[i,j], ss_res_save[i*cols + j])


# Remove x-tick labels for all plots except for the last row
for i in range(rows):
    for j in range(cols):
        if i < rows - 1:  # If not in the last row
            ax[i, j].set_xticklabels([])  # Remove x-tick labels
        else:
            ax[i, j].set_xticks(np.linspace(-np.pi,np.pi,7), ['12', '16', '20', '00', '04', '08', '12'])  # Set x-tick labels

# Add a legend at the center top of the figure
fig.legend(['Data', 'Fit', 'Basis 1', 'Basis 2', 'Basis 3'], loc='upper center', ncol=5, fontsize=16, bbox_to_anchor=(0.5, 0.9))


plt.show()

```


```{python}

# Define the column names
column_names = ['MasterID', 'Aldo', 'param_values', 'Param0', 'param1', 'param2', 'param3','param4', 'param5','param6','param7', 'param8','param9' ,'R2']

# Create a list to hold the new rows
rows = []

MasterIDs = df_com["MasterID"].unique()

for i in range(len(MasterIDs)):
    new_row = {
        'MasterID': MasterIDs[i], 
        'Aldo': num_Aldo[i],
        'param_values': basis_save[i, :],
        'Param0': basis_save[i, 0],
        'param1': basis_save[i, 1],
        'param2': basis_save[i, 2],
        'param3': basis_save[i, 3],
        'param4': basis_save[i, 4],
        'param5': basis_save[i, 5],
        'param6': basis_save[i, 6],
        'param7': basis_save[i, 7],
        'param8': basis_save[i, 8],
        'param9': basis_save[i, 9],
        'R2': ss_res_save[i]
    }
    rows.append(new_row)

# Create the DataFrame from the list of rows
df_param = pd.DataFrame(rows, columns=column_names)

# Save the dataframe to csv
df_param.to_csv("Param_values_Aldo.csv", index=False)

# Display the first few rows of dataframe
df_param.head()


```



# Cortisone

```{python}

num_Cortisone = df_to_numpy(df_com, "Cortisone")

```


```{python}

n_basis = 3
ss_res_save = np.zeros(len(num_Cortisone))
basis_save = np.zeros([len(num_Cortisone), 3*n_basis+1])
basis1 = np.zeros(3)
basis2 = np.zeros(3)
basis3 = np.zeros(3)
basis_constant = np.zeros(1)

for i in range(len(num_Cortisone)):
    print(i)
    if np.isnan(num_Cortisone[i]).any():
        continue
    res = fit_von_mises(num_Cortisone[i], 3)
    fit_params = res.x
    fit = Von_Mises_model(fit_params, t)
    basis1 = fit_params[0:3]
    basis2 = fit_params[3:6]
    basis3 = fit_params[6:9]
    basis_constant = fit_params[-1]
    
    ss_res_save[i] = NRMSE(num_Cortisone[i],fit)

    # Order the basis functions by the weight (the final parameter)
    #basis1, basis2, basis3 = order_basis(basis1, basis2, basis3)

    basis_save[i,0:3] = basis1
    basis_save[i,3:6] = basis2
    basis_save[i,6:9] = basis3
    basis_save[i,9] = basis_constant



```


```{python}

rows = 8
cols = 5
fig, ax = plt.subplots(rows,cols , figsize=(21, 28))
plt.subplots_adjust(hspace=0.1, wspace=0.15)  # Adjust space between subplots


for i in range(rows):
    for j in range(cols):
      if i*10 + j >= len(num):
          break
      plot_single(basis_save[i*cols + j,:], t, num_Cortisone[i*cols + j,:], ax[i,j], ss_res_save[i*cols + j])
      
      # Remove x-tick labels for all plots except for the last row
      if i < rows - 1:  # If not in the last row
            ax[i, j].set_xticklabels([])  # Remove x-tick labels
      else:
            ax[i, j].set_xticks(np.linspace(-np.pi,np.pi,7), ['12', '16', '20', '00', '04', '08', '12'])  # Set x-tick labels


# Add a legend at the center top of the figure
fig.legend(['Data', 'Fit', 'Basis 1', 'Basis 2', 'Basis 3'], loc='upper center', ncol=5, fontsize=16, bbox_to_anchor=(0.5, 0.9))


plt.show()

```


```{python}

# Define the column names
column_names = ['MasterID', 'Cortisone', 'param_values', 'Param0', 'param1', 'param2', 'param3','param4', 'param5','param6','param7', 'param8','param9' ,'R2']

# Create a list to hold the new rows
rows = []

MasterIDs = df_com["MasterID"].unique()

for i in range(len(MasterIDs)):
    new_row = {
        'MasterID': MasterIDs[i], 
        'Cortisone': num_Cortisone[i],
        'param_values': basis_save[i, :],
        'Param0': basis_save[i, 0],
        'param1': basis_save[i, 1],
        'param2': basis_save[i, 2],
        'param3': basis_save[i, 3],
        'param4': basis_save[i, 4],
        'param5': basis_save[i, 5],
        'param6': basis_save[i, 6],
        'param7': basis_save[i, 7],
        'param8': basis_save[i, 8],
        'param9': basis_save[i, 9],
        'R2': ss_res_save[i]
    }
    rows.append(new_row)

# Create the DataFrame from the list of rows
df_param = pd.DataFrame(rows, columns=column_names)

# Save the dataframe to csv
df_param.to_csv("Param_values_Cortisone.csv", index=False)

# Display the first few rows of dataframe
df_param.head()


```

